kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: custom-jenkins-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'custom-jenkins-rhel8:v4.12.0'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jenkins-rhel8:v4.12.0'
  source:
    type: Git
    git:
      uri: 'https://github.com/henriorespati/jenkins-s2i.git'
